
const vanillaMaps = [
    {
        game: "RollerCoaster Tycoon",
        maps: [
            "forest frontiers",
            "dynamite dunes",
            "leafy lake",
            "diamond heights",
            "evergreen gardens",
            "bumbly beach",
            "trinity islands",
            "katie's dreamland",
            "katie's world",
            "pokey park",
            "dinky park",
            "white water park",
            "aqua park",
            "millennium mines",
            "karts & coasters",
            "mel's world",
            "mystic mountain",
            "mothball mountain",
            "pacific pyramids",
            "crumbly woods",
            "paradise pier",
            "big pier",
            "lightning peaks",
            "ivory towers",
            "rainbow valley",
            "thunder rock",
            "mega park",
        ]
    },
    {
        game: "RollerCoaster Tycoon: Corkscrew Follies",
        maps: [
            "whispering cliffs",
            "three monkeys park",
            "canary mines",
            "barony bridge",
            "funtopia",
            "haunted harbour",
            "haunted harbor",
            "fun fortress",
            "future world",
            "gentle glen",
            "jolly jungle",
            "hydro hills",
            "sprightly park",
            "magic quarters",
            "fruit farm",
            "butterfly dam",
            "coaster canyon",
            "thunderstorm park",
            "harmonic hills",
            "roman village",
            "swamp cove",
            "adrenaline heights",
            "utopia park",
            "utopia",
            "rotting heights",
            "fiasco forest",
            "pickle park",
            "giggle downs",
            "mineral park",
            "coaster crazy",
            "urban park",
            "geoffrey gardens",
            "geoffery gardens",
        ]
    },
    {
        game: "RollerCoaster Tycoon: Loopy Landscapes", // RCT1 real parks
        maps: [
            "iceberg islands",
            "volcania",
            "arid heights",
            "razor rocks",
            "crater lake",
            "vertigo views",
            "paradise pier 2",
            "big pier 2",
            "dragon's cove",
            "good knight park",
            "wacky warren",
            "grand glacier",
            "crazy craters",
            "dusty desert",
            "woodworm park",
            "icarus park",
            "sunny swamps",
            "frightmare hills",
            "thunder rocks",
            "octagon park",
            "pleasure island",
            "icicle worlds",
            "southern sands",
            "tiny towers",
            "nevermore park",
            "pacifica",
            "urban jungle",
            "terror town",
            "megaworld park",
            "venus ponds",
            "micro park",
            "alton towers",
            "heide-park",
            "blackpool pleasure beach",
        ]
    },
    {
        game: "RollerCoaster Tycoon 2",
        maps: [
            "electric fields",
            "factory capers",
            "crazy castle",
            "dusty greens",
            "bumbly bazaar",
            "infernal views",
            "lucky lake",
            "botany breakers",
            "alpine adventures",
            "gravity gardens",
            "extreme heights",
            "amity airfield",
            "ghost town",
            "fungus woods",
            "rainbow summit",
            "six flags belgium",
            "six flags great adventure",
            "six flags holland",
            "six flags magic mountain",
            "six flags over texas",
        ]
    },
    {
        game: "RollerCoaster Tycoon 2: Wacky Worlds",
        maps: [
            "canyon calamities",
            "great wall of china",
            "mines of africa",
            "ayers adventure",
            "rollercoaster heaven",
            "mirage madness",
            "sugarloaf shores",
            "park maharaja",
            "over the edge",
            "wacky waikiki",
            "rainforest romp",
            "from the ashes",
            "icy adventures",
            "european extravaganza",
            "beach barbecue blast",
            "lost city founder",
            "okinawa coast",
        ]
    },
    {
        game: "RollerCoaster Tycoon 2: Time Twister",
        maps: [
            "sherwood forest",
            "crater carnage",
            "alcatraz",
            "extraterrestrial extravaganza",
            "schneider shores",
            "rocky rambles",
            "mythological madness",
            "rock n roll revival",
            "gemini city",
            "metropolis",
            "woodstock",
            "cliffside castle",
            "animatronic antics",
            "coastersaurus",
        ]
    }
]

function getSourceGame(map: string): string {
    const searchString = map.toLowerCase();
    const source = vanillaMaps.find(g => g.maps.indexOf(searchString) >= 0);
    if (source) {
        return source.game;
    }
    return 'Custom';
}

export default getSourceGame;
export { getSourceGame };
