name: Build CI Image

on:
  workflow_dispatch:
    branches: [ master ]
  repository_dispatch:
    types: [ ci-image ]
  push:
    branches: [ master ]
    paths: 
      - "ci-check/**"
  schedule:
    - cron: '0 5 * * 3'

jobs:

  build-image:
    runs-on: ubuntu-latest
    env:
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REPOSITORY: ${{ github.event.repository.name }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 2
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GH_REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=ci

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        target: deploy
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}
        context: ./ci-check/
        file: ./ci-check/Dockerfile
