name: Object Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/corysanin/ffa-tycoon-parks:ci
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 2

    - name: Pull image from GitHub Container Registry
      run: docker pull ${{ env.IMAGE }}

    - name: Run check
      run: |
        for file in ${{ github.workspace }}/parks/*/*.park; do
          docker run --rm -v ${{ github.workspace }}/parks:/parks -v ${{ github.workspace }}/object:/home/node/.config/OpenRCT2/object/custom ${{env.IMAGE}} index.js "$file"
        done
